app/site/src/Entity/Intervention.php
<?php

namespace App\Entity;

use App\Repository\InterventionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InterventionRepository::class)]
class Intervention
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Treatment $treatment = null;

    #[ORM\ManyToMany(targetEntity: Tooth::class)]
    private Collection $teeth;

    public function __construct()
    {
        $this->teeth = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTreatment(): ?Treatment
    {
        return $this->treatment;
    }

    public function setTreatment(Treatment $treatment): static
    {
        $this->treatment = $treatment;

        return $this;
    }

    /**
     * @return Collection<int, Tooth>
     */
    public function getTeeth(): Collection
    {
        return $this->teeth;
    }

    public function addTooth(Tooth $tooth): static
    {
        if (!$this->teeth->contains($tooth)) {
            $this->teeth->add($tooth);
        }

        return $this;
    }

    public function removeTooth(Tooth $tooth): static
    {
        $this->teeth->removeElement($tooth);

        return $this;
    }

    public function clearTooth(): static
    {
        $this->teeth = new ArrayCollection();
        return $this;
    }

}

app/site/src/Entity/Tooth.php
<?php

namespace App\Entity;

use App\Repository\ToothRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ToothRepository::class)]
class Tooth
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $position = null;

    #[ORM\Column]
    private ?int $position_numeric = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function getPositionNumeric(): ?int
    {
        return $this->position_numeric;
    }

    public function setPositionNumeric(int $position_numeric): static
    {
        $this->position_numeric = $position_numeric;

        return $this;
    }

}

app/site/src/Entity/Treatment.php
<?php

namespace App\Entity;

use App\Repository\TreatmentRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TreatmentRepository::class)]
class Treatment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }
}

app/site/src/Controller/MouthController.php
<?php

namespace App\Controller;

use App\Repository\ToothRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MouthController extends AbstractController
{
    #[Route('/mouth', name: 'app_mouth')]
    public function index(): Response
    {
        return $this->render('Mouth/index.html.twig');
    }

    

    #[Route('/teethList', name: 'app_teethList')]
    public function listTeeth(ToothRepository $toothRepo): Response
    {
        $teethList = $toothRepo->findAll();
        return $this->render('Mouth/teethList.html.twig', [
            'teethList' => $teethList,
        ]);
    }
}

app/site/src/Controller/SandBoxController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

class SandBoxController extends AbstractController
{
    #[Route('/sand/box', name: 'app_sand_box')]
    public function index(): JsonResponse
    {
        return $this->json([
            'message' => 'Welcome to your new controller!',
            'path' => 'src/Controller/SandBoxController.php',
        ]);
    }
}

app/site/src/Controller/TreatmentController.php
<?php

namespace App\Controller;

use App\Entity\Intervention;
use App\Repository\ToothRepository;
use App\Repository\TreatmentRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\InterventionRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TreatmentController extends AbstractController
{
    #[Route('/treatment', name: 'app_treatment')]
    public function index(TreatmentRepository $treatmentRepo): Response
    {
        $treatments = $treatmentRepo->findAll();

        return $this->render('treatment/index.html.twig', [
            'treatments' => $treatments
        ]);
    }

    #[Route('/list_inventions', name: 'app_list_inventions')]
    public function listInventions(InterventionRepository $invRepo): Response
    {
        $inv = $invRepo->findAll();

        return $this->render('treatment/inventions.html.twig', [
            'inventions' => $inv
        ]);
    }

    #[Route('/save_intervetion', name: 'app_save_intervetion')]
    public function saveIntervention(EntityManagerInterface $entityManager, Request $request, TreatmentRepository $treatmentRepo, 
        ToothRepository $toothRepo, InterventionRepository $interventionRepo): JsonResponse
    {

        $inv = $interventionRepo->findOneBy(['treatment'=> $treatmentRepo->findOneBy(['id'=> $request->get('treatment')])]);
        
        if( $inv == null) {
            $inv = new Intervention();
        }

        $inv->setTreatment($treatmentRepo->findOneBy(['id'=> $request->get('treatment')]));
        $teeth = $request->get('teeth');
        $inv->clearTooth();
        if($request->get('teeth') != null)
            foreach ($request->get('teeth') as $tooth_id) {
                $inv->addTooth($toothRepo->findOneBy(['id'=>$tooth_id]));
            }

        $entityManager->persist($inv);
        $entityManager->flush();

        return $this->json([
            'message' => 'Welcome to your new controller!',
            'path' => 'src/Controller/SandBoxController.php',
        ]);
    }

    #[Route('/listTeethByInventions', name: 'app_list_inventions_by_treatment')]
    public function listInventionsByTreatment(Request $request, InterventionRepository $invRepo, TreatmentRepository $treatmentRepo): JsonResponse
    {
        $inv = $invRepo->findOneBy(['treatment' => $treatmentRepo->findOneBy(['id'=> $request->get('treatment_id')])]);
        //dd( $request->get('treatment_id') );
        return $this->json( $inv->getTeeth() );
    }

    #[Route('/deleteInvention', name: 'app_delete_invention')]
    public function deleteInvention(Request $request, InterventionRepository $invRepo, EntityManagerInterface $em): JsonResponse
    {
        $sql = "delete from intervention where treatment_id = ".$request->get('id');
        

        return $this->json([
            'success' => $em->getConnection()->exec($sql),
            'sql' => $sql,
        ]);
    }
}

app/site/templates/Mouth/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Open your mouth!
{% endblock %}

{% block body %}

	<div class="row gx-2" style="border: 1px solid red;">
		<div class="col-auto">
			<h5>Kezelések</h5>
			{{ render(url( 'app_treatment' )) }}
		</div>
		<div class="col-auto">
			<h5>Fogkép</h5>
			<div id="teethListDiv">{{ render(url( 'app_teethList' )) }}</div>
		</div>
	</div>

<script>
    $('#save_treatment').click(function(){
        teethList = [];
        $('.cb_teeth:checkbox:checked').each(function(){
            teethList.push( $(this).attr('tdid') );
        });

        $.ajax({
            url: "/save_intervetion",
            method: "POST",
            data: {treatment: $('#treatment_list').val(), teeth: teethList}
        }).done(function() {
            $.get("/list_inventions", function( data ) {
                $('#list_inventions').html( data );
            });
            //@TODO: load the invention into list on the left side!!!
        });
    });

	$(document).on('click', '.invention_btn', function () {
		$('#treatment_list').val( $(this).attr('id') );
        $.ajax({
            url: "/listTeethByInventions",
            method: "POST",
            data: {treatment_id: $(this).attr('id')}
        }).done(function(data) {
            initTeeth();
            $.each(data, function(index, item){
                $('#teethListTable #cb_teeth_'+item.id).prop( "checked", true );
                $('#teethListTable #'+item.id).addClass('selected_td');
            });
        });
    });

    function initTeeth(){
        $('#teethListTable .cb_teeth').prop( "checked", false );
        $('#teethListTable td').removeClass('selected_td');
    }

	$(document).on('click', '.delete-invention', function () {
		console.log();
		$.ajax({
            url: "/deleteInvention",
            method: "POST",
            data: {id: $(this).prev().attr('id')}
        }).done(function(data) {
            console.log( data );
			$.get("/list_inventions", function( data ) {
                $('#list_inventions').html( data );
            });
        });
	});
</script>

{% endblock %}

app/site/templates/Mouth/teethList.html.twig
<style>
    td { padding: 10px !important ; border: 1px solid black; background-color: white; }
    td:hover { cursor: pointer; background-color: green; }
    .selected_td { border: 3px solid blue !important;}
</style>
<table class="table-bordered" id="teethListTable">
    <tr>
    {% for teeth in teethList %}
        <td class="teeth_td" id="{{teeth.id}}"> 
            {{ teeth.positionNumeric }} 
            <input type="checkbox" id="cb_teeth_{{teeth.id}}" tdid="{{teeth.id}}" class="d-none cb_teeth" /></td>
        {% if loop.index == 16 %} </tr><tr> {% endif %}
    {% endfor %}
    </tr>
</table>

<script>
    $('.teeth_td').click(function(){
        if($('#cb_teeth_'+$(this).attr('id')).prop('checked')){
            $('#cb_teeth_'+$(this).attr('id')).prop( "checked", false );
            $(this).removeClass('selected_td');
        }else{
            $('#cb_teeth_'+$(this).attr('id')).prop( "checked", true );
            $(this).addClass('selected_td');
        }
    });
</script>

app/site/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
         <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
            <script src="https://kit.fontawesome.com/3aa6018d36.js" crossorigin="anonymous"></script>
            
            <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
	        <script src="https://jquery.com/wp-content/themes/jquery/js/main.js"></script>
        {% endblock %}
    </head>
    <body>
        <div class="container">
            {% block body %}{% endblock %}
        </div>
    </body>
</html>

app/site/templates/treatment/index.html.twig
<div class="container">
    <div class="row">
        <div class="col">
            <select class="form-select form-select-sm" aria-label=".form-select-lg" id="treatment_list">
                <option selected>Válasszon kezelést</option>
                {% for treatment in treatments %}
                    <option value="{{ treatment.id }}">{{ treatment.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col">
            <button type="button" class="btn btn-success btn-sm" id="save_treatment">Rögzítés</button>
        </div>
    </div>
    <div class="row mt-1" id="list_inventions">
        {{ render(url( 'app_list_inventions' )) }}
    </div>
</div>

app/site/templates/treatment/inventions.html.twig
<ul class="list-group">
    {% for invention in inventions %}
        <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action" >
            <div class="container invention_btn" style="cursor: pointer;" id="{{ invention.treatment.id }}">{{ invention.treatment.name }} [{% for tooth in invention.teeth %}{{ tooth.positionNumeric }}{% if loop.last %}{% else %},{% endif %}{% endfor %}]
        </div>
            <span class="badge badge-primary badge-pill delete-invention" style="border: 1px solid red; cursor: pointer;">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-trash" viewBox="0 0 16 16">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"></path>
                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"></path>
                </svg>
            </span>
        </li>
    {% endfor %}
</ul>